apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spidey 
  namespace: spidey
spec:
  minReadySeconds: 5
  replicas: 3
  template:
    metadata:
      labels:
        name: spidey
    spec:
      containers:
      - name: spidey
        image: undeadops/webby:feature01-97a721a
        ports:
        - containerPort: 5000
