apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: foobar
  namespace: foobar
spec:
  minReadySeconds: 5
  replicas: 3
  template:
    metadata:
      labels:
        name: foobar
    spec:
      containers:
      - name: foobar
        image: undeadops/webby:master-f619e5d
        ports:
        - containerPort: 5000
